In [7]:
import numpy as np

data = np.genfromtxt("BOII_SR_2000to2017.csv", delimiter=',')

TypeError: genfromtxt() got an unexpected keyword argument 'header'

In [4]:
print(data)

[[             nan              nan              nan              nan]
 [  2.00000000e+03   1.00000000e+01   1.00000000e+00   9.96143456e+00]
 [  2.00000000e+03   1.00000000e+01   2.00000000e+00   1.17665419e+01]
 ..., 
 [  2.01700000e+03   9.00000000e+00   2.80000000e+01   1.23644857e+01]
 [  2.01700000e+03   9.00000000e+00   2.90000000e+01   1.22046903e+01]
 [  2.01700000e+03   9.00000000e+00   3.00000000e+01   1.10149239e+01]]
